### ISSUE TITLE
Bandpass filters

### ISSUE THREAD

**Issue by florian6973** [msdkhani/PyWaveClus#1]
Hi!

I am trying to use the new Python waveclus version, but I cannot reproduce the good Matlab results. Could someone please clarify
```
recording_bp2 = ...  # Preprocessed recording (bandpass 2)
recording_bp4 = ...  # Preprocessed recording (bandpass 4)
```
? Indeed, I am currently bandpassing between 300 et 3000 Hz. Should I use filters of different orders (2 and 4) ?

Thanks :)

**Comment by msdkhani** [comment]
> Hi!
> 
> I am trying to use the new Python waveclus version, but I cannot reproduce the good Matlab results. Could someone please clarify
> 
> ```
> recording_bp2 = ...  # Preprocessed recording (bandpass 2)
> recording_bp4 = ...  # Preprocessed recording (bandpass 4)
> ```
> 
> ? Indeed, I am currently bandpassing between 300 et 3000 Hz. Should I use filters of different orders (2 and 4) ?
> 
> Thanks :)

Hi, 
For this pipeline we used the second and fouth order of bandpass filter. You can Find more detailed information about how to run it here:
https://github.com/msdkhani/SpikeSorting/blob/main/main.ipynb

**Comment by florian6973** [comment]
Perfect, thank you so much!
